services:
  web:
    build: .
    command: /djangocker/build_files.sh
    volumes:
      - ./media:/djangocker/media
      - ./staticfiles:/djangocker/staticfiles
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./staticfiles:/djangocker/staticfiles
      - ./media:/djangocker/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: postgres:15
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  pgdata:
