services:
  web:
    build: .
    command: /djangocker/build_files.sh
    volumes:
      - ./media:/djangocker/media
      - ./staticfiles:/djangocker/staticfiles
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - web
    volumes:
      - ./staticfiles:/djangocker/staticfiles
      - ./media:/djangocker/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: postgres:latest
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5431:5432"

volumes:
  pgdata:
